version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: "v0.9.x"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "v0.9.x"
    schedule:
      interval: monthly
